### ISSUE TITLE
Add lifecycle input

### ISSUE THREAD

**Issue by jlory** [mongodb/terraform-aws-ecs-task-definition#16]
Hi, I'm not sure how you use the module but it's very common to manage ECS task def by Terraform and then update the image version using a different tool ( like a CI/CD pipeline) , so it would be nice to have the option to pass an array for the lifecycle block, then Terraform won't complain if you change the image version outside of the module. Thoughts?

Ex:

```
  lifecycle {
    ignore_changes = [image]
  }
```

**Comment by jasonwalsh** [comment]
HI @jlory, this is feasible. Feel free to submit a pull request with this new feature, otherwise I can implement it in the next release.

**Comment by jlory** [comment]
Actually I checked the doc and it doesn't seems possible :/
https://www.terraform.io/docs/configuration/resources.html

> The lifecycle settings all effect how Terraform constructs and traverses the dependency graph. **As a result, only literal values can be used** because the processing happens too early for arbitrary expression evaluation.
