### ISSUE TITLE
aws_ecs_task_definition invalid: volume must be a block not an attribute

### ISSUE THREAD

**Issue by chgerkens** [mongodb/terraform-aws-ecs-task-definition#20]
Error: Unsupported argument

  on .terraform/modules/my-task-definition/main.tf line 181, in resource "aws_ecs_task_definition" "ecs_task_definition":
 181:   volume                   = "${var.volumes}"

An argument named "volume" is not expected here. Did you mean to define a
block of type "volume"?

Refer to: 
https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html#volume-block-arguments

**Comment by jasonwalsh** [comment]
@chgerkens can you paste your Terraform config? It's possible that this may be related to #17.

**Comment by MooreDerek** [comment]
The Terraform is expecting a block (https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html) but the code is trying to pass through a variable: 

`resource "aws_ecs_task_definition" "ecs_task_definition" {
  container_definitions    = "${local.container_definitions}"
  execution_role_arn       = "${var.execution_role_arn}"
  family                   = "${var.family}"
  ipc_mode                 = "${var.ipc_mode}"
  network_mode             = "${var.network_mode}"
  pid_mode                 = "${var.pid_mode}"
  placement_constraints    = "${var.placement_constraints}". <-- This need to be a block
  requires_compatibilities = "${var.requires_compatibilities}"
  task_role_arn            = "${var.task_role_arn}"
  volume                   = "${var.volumes}" <-- This needs to be a block

  count = "${var.register_task_definition ? 1 : 0}"
}`

**Comment by laur1s** [comment]
```
 Error: Unsupported argument

  on .terraform/modules/pdf_api.mongo-task-definition/main.tf line 178, in resource "aws_ecs_task_definition" "ecs_task_definition":
 178:   placement_constraints    = "${var.placement_constraints}"

An argument named "placement_constraints" is not expected here. Did you mean
to define a block of type "placement_constraints"?


Error: Unsupported argument

  on .terraform/modules/pdf_api.mongo-task-definition/main.tf line 181, in resource "aws_ecs_task_definition" "ecs_task_definition":
 181:   volume                   = "${var.volumes}"

An argument named "volume" is not expected here. Did you mean to define a
block of type "volume"?
```
More errors. I could submit the PR to fix this issue. But not sure if this module is maintained if critical issue is unfixed for so long

**Comment by jasonwalsh** [comment]
@laur1s feel free to submit a PR.
