### ISSUE TITLE
module is giving error while plan

### ISSUE THREAD

**Issue by manojks5540** [mongodb/terraform-aws-ecs-task-definition#21]
Error: Error running plan: 3 errors occurred:
	* module.ecs-task-definition.output.family: Resource 'aws_ecs_task_definition.ecs_task_definition' does not have attribute 'family' for variable 'aws_ecs_task_definition.ecs_task_definition.*.family'
	* module.ecs-task-definition.output.revision: Resource 'aws_ecs_task_definition.ecs_task_definition' does not have attribute 'revision' for variable 'aws_ecs_task_definition.ecs_task_definition.*.revision'
	* module.ecs-task-definition.output.arn: Resource 'aws_ecs_task_definition.ecs_task_definition' does not have attribute 'arn' for variable 'aws_ecs_task_definition.ecs_task_definition.*.arn'

**Comment by jasonwalsh** [comment]
What version of Terraform are you using?

**Comment by manojks5540** [comment]
Terraform v0.11.14
+ provider.aws v2.45.0 

we are running in enterprise workspace through cli..

**Comment by manojks5540** [comment]
if I run locally it works fine but, in remote workspace it gives error.

**Comment by manojks5540** [comment]
Sorry my bad, I was $ was missing in container port variable while declaring, it's working fine now, thank you for the help, I'm closing this.
