### ISSUE TITLE
Type of logConfiguration makes it impossible to add awslogs options

### ISSUE THREAD

**Issue by krcz** [mongodb/terraform-aws-ecs-task-definition#26]
Type of `logConfiguration` field in this module is `map(string)` which means that adding subdictionary under `options` key is impossible while it is a common usage pattern:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html#specify-log-config

**Comment by jasonwalsh** [comment]
@krcz it should be fixed now. Please try using the latest release.

**Comment by krcz** [comment]
@jasonwalsh Veryfied, it works perfectly, thank you!
