### ISSUE TITLE
replace function in the code

### ISSUE THREAD

**Issue by ShitulGupta** [mongodb/terraform-aws-ecs-task-definition#30]
Can someone please explain how does the below code snippet function:

container_definitions = replace(local.container_definition, "/\"(null)\"/", "$1")

will it replace all the "null" occurrences with null again , I am confused a quick help is really appreciated.

Thanks & Regards

**Comment by ShitulGupta** [comment]
I do not get the purpose of using replace function here.

**Comment by jasonwalsh** [comment]
This module was written before Terraform 0.12 existed, so `null` was not a valid data type in Terraform configuration files.

The `replace` function removes quotes surrounding all occurrences of `"null"`.

For example, [this](https://github.com/mongodb/terraform-aws-ecs-task-definition/blob/master/main.tf#L94) line uses a ternary expression to check if the `command` directive is an empty array, and if so, it evaluates to `"null"`.

Before Terraform 0.12, ternary expressions only worked with string and number data types, so the following does not work:

```
command = length(var.command) == 0 ? null : var.command
```

`"null"` evaluates as a string in JSON, but the accepted data types for the `command` directive are either an array of strings *or* null, so the `replace` function is required to remove the quotes surrounding the `null` type.
