### ISSUE TITLE
secrets

### ISSUE THREAD

**Issue by dannymoscoso** [mongodb/terraform-aws-ecs-task-definition#43]
This module works great, however im having difficulties with secrets

its not taking:    
```

secrets = [{
      name  = "secret"
      valueFrom = "${data.aws_secretsmanager_secret_version.db.arn}"
    }]

```
what is the proper way to get secrets into the container ?

**Comment by dannymoscoso** [comment]
changed required type for secrets on a fork, thanks!

**Comment by jasonwalsh** [comment]
@dannymoscoso would you mind submitting a PR with the changes made in your fork?
