### ISSUE TITLE
Secrets Variable of Wrong Type

### ISSUE THREAD

**Issue by sethsaperstein** [mongodb/terraform-aws-ecs-task-definition#44]
Secrets in variables is listed as list(string) but per aws documentation, the format of a secret is as follows: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Secret.html

Thus type should be list(map(string)) since secrets is later json encoded.
Correct me if I'm using this improperly of course :)

**Comment by davidstoker** [comment]
I ran into this trying to use this module as well. In current form, a `list(any)` to be similar to other fields like `portMappings` would work. A more proper definition could be used too since it's a defined format as seen in the docs:

```
type = list(object({
    name      = string
    valueFrom = string
  }))
```
