### ISSUE TITLE
Tags are not used?

### ISSUE THREAD

**Issue by g-dury** [mongodb/terraform-aws-ecs-task-definition#47]
Hi,

Thank you for the wonderful work on this.
Just a quick question around `tags`. It's written in the docs that you support tags as variable but I do not see them registered anywhere afterward (not in the Task definition, nor in the Task itself)
Should we just remove it from the README and variables.tf? Or do you want me to PR what I will do to add them to the resources?

Thank you very much!
Best regards,

**Comment by jasonwalsh** [comment]
Hi @g-dury 

Nice catch! The `tags` field is used by the [`ecs_task_definition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#tags) resource, so it makes sense to add the missing field.

Would you mind submitting a PR?

Thank you.

**Comment by g-dury** [comment]
Hey,

No problem, I actually realised what I was looking for was also to propagate tags to the task level, which is something done at the service level by the field "propagate_tags" in aws_ecs_service resources, FYI :)
Here's the PR: https://github.com/mongodb/terraform-aws-ecs-task-definition/pull/48
