### ISSUE TITLE
Template provider is deprecated

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [mongodb/terraform-aws-ecs-task-definition#59]
This module still uses `template` provider despite it [was archived](https://github.com/hashicorp/terraform-provider-template/issues/85) back in 2020. The solution is to replace it with `templatefile` function.

https://github.com/mongodb/terraform-aws-ecs-task-definition/blob/d95413d9eb7f046aaa4b66c990680a0ad32d1ab3/main.tf#L90

**Comment by mateuszkwiatkowski** [comment]
PR provided by @Skardian worked for me. Please merge. 👍

**Comment by djwaix** [comment]
Any ETA on this PR being merged?
this module is the last in our infra that's hanging onto the `hashicorp/template` plugin.
