### ISSUE TITLE
version 0.1.0 removed from registry?

### ISSUE THREAD

**Issue by ccann** [mongodb/terraform-aws-ecs-task-definition#7]
Hi!

Thanks for sharing this template.

I had just finished adapting some of our modules to build off of version 0.1.0 of this template and now a few days later:
```
Error downloading modules: Error loading modules: no versions for "mongodb/ecs-task-definition/aws" found matching "0.1.0"
```

I see that there are versions 1.0.0, 1.0.1, 1.1.0 now available. Does one of those version map to 0.1.0? 

My biggest concern is that the version disappeared from the registry. I didn't realize artifacts could/would disappear. If that's the case I'll have to fork.

**Comment by jasonwalsh** [comment]
Hi @ccann! Thanks for opening this! It is safe to use `1.1.0`. I recently integrated [`semantic-release`](https://github.com/semantic-release/semantic-release) as part of the CircleCI config and removed the previous release (`0.1.0`).

```hcl
module "ecs-task-definition" {
  source  = "mongodb/ecs-task-definition/aws"
  version = "1.1.0"

  # insert the 1 required variable here
}
```

Should work fine. Please let me know if you experience any more issues.

**Comment by ccann** [comment]
Thanks!
