### ISSUE TITLE
How to create a task with multiple container definitions

### ISSUE THREAD

**Issue by ccann** [mongodb/terraform-aws-ecs-task-definition#9]
Is it possible to use this template to create a task with multiple container definitions? 
The output is an array so it seems like it's set up to do that, it just wasn't clear to me how to achieve it with inputs like `cpu` or `memory` -- how would I use this template to create two containers with different CPU and memory reservations?

**Comment by jasonwalsh** [comment]
Hi @ccann! This feature is currently not supported and is a bit difficult to implement in Terraform v0.11.x. However, I'll try to mess around and see what I can come up with. Thanks.

**Comment by jasonwalsh** [comment]
@ccann I've added support for this in [`v1.2.0`](https://github.com/mongodb/terraform-aws-ecs-task-definition/releases/tag/v1.2.0).

**Comment by ccann** [comment]
wow, this rules. thanks!!
